---
apiVersion: v1
kind: Service
metadata:
    name: order-service
    namespace: backend
    labels:
        app: order-service
        component: microservice
        tier: backend
spec:
    type: ClusterIP # Internal only - accessed via Kong Gateway
    ports:
        - port: 8001
          targetPort: 8001
          protocol: TCP
          name: http
    selector:
        app: order-service
