---
apiVersion: v1
kind: Secret
metadata:
    name: payment-service-secret
    namespace: backend
type: Opaque
stringData:
    STRIPE_SECRET_KEY: "REPLACE_WITH_ENV_VAR_STRIPE_SECRET_KEY"
    STRIPE_WEBHOOK_SECRET: "REPLACE_WITH_ENV_VAR_STRIPE_WEBHOOK_SECRET"
