---
apiVersion: v1
kind: Secret
metadata:
    name: product-service-secret
    namespace: backend
type: Opaque
stringData:
    # Add sensitive environment variables here
    # DATABASE_PASSWORD: "your-secure-password"
    # API_KEY: "your-api-key"
