---
apiVersion: v1
kind: Service
metadata:
    name: product-service
    namespace: backend
    labels:
        app: product-service
        component: microservice
        tier: backend
spec:
    type: ClusterIP # Internal only - accessed via Kong Gateway
    ports:
        - port: 8000
          targetPort: 8000
          protocol: TCP
          name: http
    selector:
        app: product-service
