version: "3.8"

services:
  # 1. Database: Postgres (Dành cho Product Service)
  postgres:
    image: postgres:15
    container_name: nt2205-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Identity: Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: nt2205-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      # Bạn cần export realm hiện tại của bạn ra file này để teammate có sẵn config
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  # 3. Message Queue: Kafka & Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: nt2205-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"

  kafka:
    image: bitnamilegacy/kafka:latest
    container_name: nt2205-kafka
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: nt2205-kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka

volumes:
  postgres_data:
