version: "3.8"

services:
  # 1. Database: Postgres
  postgres:
    image: postgres:15-alpine # Nên dùng bản alpine cho nhẹ
    container_name: nt2205-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    # Dữ liệu bền vững (Persistence)
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # (Tuỳ chọn) Mount file init.sql nếu bạn dùng Cách 2 ở trên
      # - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. Identity: Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: nt2205-keycloak
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      # File này phải có trên Git để đồng bộ cấu hình Realm
      - ./docker/keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json

  # 3. Message Queue: Kafka (Chế độ Kraft - Không cần Zookeeper)
  kafka:
    image: bitnamilegacy/kafka:4.0.0-debian-12-r10 # Pin đúng version từ file package của bạn
    container_name: nt2205-kafka
    environment:
      # Cấu hình Kraft mode
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_KRAFT_CLUSTER_ID: 7Dvn0OLMQo-bg4qmCmflVg
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: nt2205-kafka-ui
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  postgres_data:
